# Generated by Django 5.2.7 on 2026-01-21 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_payment_method'),
        ('payments', '0002_alter_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway_name',
            field=models.CharField(default='esewa', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('net_banking', 'Net Banking'), ('upi', 'UPI'), ('wallet', 'Digital Wallet'), ('cod', 'Cash on Delivery'), ('esewa', 'eSewa')], max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_name', models.CharField(default='Pharmazone', max_length=200)),
                ('company_address', models.TextField(default='Kathmandu, Nepal')),
                ('company_phone', models.CharField(default='+977-1-4567890', max_length=20)),
                ('company_email', models.EmailField(default='info@pharmazone.com.np', max_length=254)),
                ('company_website', models.URLField(default='https://pharmazone.com.np')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(default='Payment is due within 30 days. Thank you for your business!')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice_number'], name='payments_in_invoice_3fa711_idx'), models.Index(fields=['order'], name='payments_in_order_i_7a414b_idx'), models.Index(fields=['status'], name='payments_in_status_45b876_idx')],
            },
        ),
    ]
