# Generated by Django 5.2.7 on 2026-01-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_token_created',
        ),
    ]
