# Generated by Django 5.2.7 on 2026-01-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash Payment')], default='cash', max_length=20),
        ),
    ]
