# Generated by Django 5.2.7 on 2025-10-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=models.CharField(default='Nepal', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default='Nepal', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='Nepal', max_length=100),
        ),
    ]
