# Generated by Django 5.2.7 on 2025-11-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_billing_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('esewa', 'eSewa'), ('khalti', 'Khalti')], default='cod', max_length=20),
        ),
    ]
